services:
  web1:
    image: my-nginx-container
    ports:
      - "8080:80"

  web2:
    image: my-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./unique/index1.html:/usr/share/nginx/html/index.html

  web3:
    image: my-nginx-container
    ports:
      - "8082:80"
    volumes:
      - ./unique/index2.html:/usr/share/nginx/html/index.html

  web4:
    image: my-nginx-container
    ports:
      - "8083:80"
    volumes:
      - ./unique/index3.html:/usr/share/nginx/html/index.html

  web5:
    image: my-nginx-container
    ports:
      - "8084:80"
    volumes:
      - ./unique/index4.html:/usr/share/nginx/html/index.html

  web6:
    image: my-nginx-container
    ports:
      - "8085:80"
    volumes:
      - ./unique/index5.html:/usr/share/nginx/html/index.html

